# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ae170c77cf98e3ee5943d04a5166aad38b54de8dfb6aa9809bd155878ca7a8ead3dee16f77ce883742fdd269ff86d3608efd7a58f3eebfaf00c70a73ab206c

test:
  secret_key_base: d48d676e496933469de969077bb3def9d8357de6e0db7e89aa5c134c8861d96e0df435c0560b801ce5b204b1078ecb44aeff0ac3ef66043343c5c3ef54b5d403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
